// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmaryuhfiftzleqtlgos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtYXJ5dWhmaWZ0emxlcXRsZ29zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NzAwNDMsImV4cCI6MjA2NDA0NjA0M30.GicKq41Lr3Z3QddtqrE8uhUaQ1Uf8YJU8OvdD1t8dEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);